modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="blockblocker" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Block Blocker" #mandatory

credits="Mojang for making not providing a way to inherently prohibit the use or breaking of blocks" #optional

authors="Kreezxil, Eleksploded" #optional

description='''
A prevention system for block breaking and placement
'''